# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a200tfbg484-3

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/csusatama/Documentos/pryectoaudiovivado/transmision/transmision.cache/wt [current_project]
set_property parent.project_path /home/csusatama/Documentos/pryectoaudiovivado/transmision/transmision.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog /home/csusatama/Documentos/pryectoaudiovivado/casm/divisor.vh
read_verilog -library xil_defaultlib {
  /home/csusatama/Documentos/pryectoaudiovivado/casm/generadorbaudios.v
  /home/csusatama/Documentos/pryectoaudiovivado/casm/myram.v
  /home/csusatama/Documentos/pryectoaudiovivado/casm/trasmitir.v
  /home/csusatama/Documentos/pryectoaudiovivado/casm/uart.v
  /home/csusatama/Documentos/pryectoaudiovivado/casm/buffer.v
  /home/csusatama/Documentos/pryectoaudiovivado/casm/divisor.v
  {/home/csusatama/Documentos/pryectoaudiovivado/casm/spectrum-2 (1).v}
}
synth_design -top spectrum -part xc7a200tfbg484-3
write_checkpoint -noxdef spectrum.dcp
catch { report_utilization -file spectrum_utilization_synth.rpt -pb spectrum_utilization_synth.pb }
